version: '3.8'
services:
  backend:
    build: ./Back_end
    ports:
      - "3001:3001"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  frontend:
    build: ./Front_end/front_end
    ports:
      - "5173:5173"
    depends_on:
      - backend